print("                          ________  ")
print("                __________|______|_______")
print("               /            |\ |         \.")
print("              /             | \|          \.")
print("             /                             \.")
print("            /                               \.")
print("           /                                 \.")
print("          /                                   \.")
print("         /                                     \.")
print("         |                   /\                |")
print("         |                  /  \               |")
print("         |                 /  N \           __ |")
print("         | \  /\  /       /______\         |_  |")
print("         |  \/  \/        \      /         |__ |")
print("         |                 \ S  /              |")
print("         |                  \  /               |")
print("         \                   \/                /")
print("          \                                   /")
print("           \                                 /")
print("            \              __               /")
print("             \             |_              /")
print("              \            __|            /")
print("               \_________________________/")


