print(r"                  ______  ")
print(r"                 /      \ ")
print(r"                /        \         ------> Pirate hat")
print(r"            ___/          \___ ")
print(r"           |__________________|    ")
print(r"              |       \__   |  ")
print(r"              | ( * ) {__}  |      ------> Eye patch")
print(r"              \          \ / ")
print(r"               \  [----] /  ")
print(r"                \________/     ")
print(r"            _______|   |_______     ")
print(r"           /                   \          ")
print(r"          /                     \          ")
print(r"         /   /|              |\  \          ")
print(r"        /   / |              | \  \           ")
print(r"       /   /  |              |  \  \            ")
print(r"      /   /   |              |   \  \          ")
print(r"     /   /    |              |    \  \          ")
print(r"    /___/     |______________|     \__\           ")
print(r"    / /       |              |       \.\__")
print(r"   / /        |      ___     |            \.    ------> Hook")
print(r"  /_/         |     |   |    |         (___)")
print(r"              |     |   |    |")
print(r"              |     |   |    |")
print(r"              |     |   |    |")
print(r"              |     |   |    |")
print(r"              |     |   |    |")
print(r"              |_____|   |____|")
print(r"                |  |     |  |")
print(r"                |  |     |  |")
print(r"                |  |     |  |")
print(r"                |__|     \__/        ------> Wooden leg")
